services:
    frontend-prod:
        container_name: frontend-prod
        ports:
            - '80:80'
            - '443:443'
        build:
            context: ../frontend
            dockerfile: dockerfile.prod
        volumes:
            - ../nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        depends_on:
            - certbot-prod
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    certbot-prod:
        container_name: certbot-prod
        image: certbot/certbot
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"

    backend-prod:
        container_name: backend-prod
        ports:
            - '3000:3000'
        build:
            context: ../backend
            dockerfile: dockerfile.prod
        volumes:
            - ../backend:/app
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always

    db-prod:
        container_name: db-prod
        ports:
            - '3306:3306'
        image: mariadb:latest
        volumes:
            - collection_data:/var/lib/mysql
            - /etc/letsencrypt:/etc/letsencrypt
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: collection_db_1988
            MYSQL_DATABASE: collection

volumes:
    collection_data:

networks:
    default:
        name: ${NETWORK_NAME_PROD}
